export const teams =[
    {id:1, src: '../../../images/teams/ethiniki-ellados.PNG', label:'ethiniki ellados'},
    {id:2, src: '../../../images/teams/aek.PNG', label:'aek'},
    {id:3, src: '../../../images/teams/ael.PNG', label:'ael'},
    {id:4, src: '../../../images/teams/appolon.PNG', label:'appolon'},
    {id:5, src: '../../../images/teams/asteras.PNG', label:'asteras'},
    {id:2, src: '../../../images/teams/atromitos.PNG', label:'atromitos'},
    {id:6, src: '../../../images/teams/lamia.PNG', label:'lamia'},
    {id:7, src: '../../../images/teams/aris.PNG', label:'aris'},
    {id:8, src: '../../../images/teams/osfp.PNG', label:'olympiakos'},
    {id:9, src: '../../../images/teams/pao.PNG', label:'panathinaikos'},
    {id:10, src: '../../../images/teams/panaitolikos.PNG', label:'panaitolikos'},
    {id:11, src: '../../../images/teams/panionios.PNG', label:'panionios'},
    {id:12, src: '../../../images/teams/paok.PNG', label:'paok'},
    {id:13, src: '../../../images/teams/pas.PNG', label:'pas giannena'},
    {id:14, src: '../../../images/teams/ofi.PNG', label:'ofi'},
    {id:15, src: '../../../images/teams/volos.PNG', label:'volos'},
    {id:16, src: '../../../images/teams/ionikos.PNG', label:'ionikos'},
    {id:17, src: '../../../images/teams/super-league.PNG', label:'super-league'},
    {id:18, src: '../../../images/teams/super-league-2.PNG', label:'super-league-2'},
    {id:19, src: '../../../images/teams/premier-league.PNG', label:'premier-league'},
    {id:20, src: '../../../images/teams/la-liga.PNG', label:'la-liga'},
    {id:21, src: '../../../images/teams/serie-a.PNG', label:'serie-a'},
  
]